name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - uses: lowlighter/metrics@latest
        
        with:
          plugin_languages: yes
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          
          token: ${{ secrets.TOKEN }}
